### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by jbrooksuk** [DivineOmega/cachet.js#2]
Add to bower.io and this is perfect!

**Comment by Jord-JD** [comment]
Thanks James. I'll register it on bowser soon.

**Comment by Jord-JD** [comment]
Done. :) Install with:

bower install cachet.js

**Comment by jbrooksuk** [comment]
Awesome! :D

**Comment by jbrooksuk** [comment]
I've linked you on the docs; http://cachet.readme.io/v1.0/docs/client-libraries

**Comment by jbrooksuk** [comment]
For some reason our CNAME has cached.

**Comment by Jord-JD** [comment]
Thanks for the link. :+1:

**Comment by jbrooksuk** [comment]
No problem!
